"""
CDK stack for the HPV MLOps pipeline -- parallel "v2" infrastructure.
Builds incrementally, same pattern as the rest of this project. This
version adds all 7 IAM roles on top of the S3 bucket + DynamoDB table
from the previous step.
"""

from aws_cdk import (
    Stack,
    RemovalPolicy,
    Duration,
    aws_s3 as s3,
    aws_s3_deployment as s3_deployment,
    aws_dynamodb as dynamodb,
    aws_iam as iam,
    aws_glue as glue,
    aws_lambda as lambda_,
    aws_stepfunctions as sfn,
    aws_events as events,
    aws_events_targets as targets,
)
from constructs import Construct


class HpvMlopsStack(Stack):
    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        # ------------------------------------------------------------------
        # Storage
        # ------------------------------------------------------------------
        self.bucket = s3.Bucket(
            self, "HpvMlopsBucket",
            removal_policy=RemovalPolicy.DESTROY,
            auto_delete_objects=True,
        )

        self.table = dynamodb.Table(
            self, "HpvRiskScoresTable",
            table_name="hpv-risk-scores-v2",
            partition_key=dynamodb.Attribute(name="person_id", type=dynamodb.AttributeType.STRING),
            billing_mode=dynamodb.BillingMode.PAY_PER_REQUEST,
            removal_policy=RemovalPolicy.DESTROY,
        )

        # ------------------------------------------------------------------
        # IAM roles -- role names are auto-generated by CDK (not hardcoded),
        # same reasoning as the bucket: avoids any collision with the
        # existing manually-created roles of the same conceptual purpose.
        # ------------------------------------------------------------------

        # 1. Glue ETL role
        self.glue_role = iam.Role(
            self, "GlueEtlRole",
            assumed_by=iam.ServicePrincipal("glue.amazonaws.com"),
            managed_policies=[
                iam.ManagedPolicy.from_aws_managed_policy_name("service-role/AWSGlueServiceRole")
            ],
        )
        self.bucket.grant_read_write(self.glue_role)

        # 2. SageMaker Processing role
        self.sm_processing_role = iam.Role(
            self, "SmProcessingRole",
            assumed_by=iam.ServicePrincipal("sagemaker.amazonaws.com"),
        )
        self.bucket.grant_read_write(self.sm_processing_role)
        self.sm_processing_role.add_to_policy(iam.PolicyStatement(
            actions=["logs:CreateLogGroup", "logs:CreateLogStream", "logs:PutLogEvents"],
            resources=[f"arn:aws:logs:{self.region}:{self.account}:log-group:/aws/sagemaker/*"],
        ))

        # 3. SageMaker Training role (same permission shape as Processing,
        # kept as a separate role/object for least-privilege task separation)
        self.sm_training_role = iam.Role(
            self, "SmTrainingRole",
            assumed_by=iam.ServicePrincipal("sagemaker.amazonaws.com"),
        )
        self.bucket.grant_read_write(self.sm_training_role)
        self.sm_training_role.add_to_policy(iam.PolicyStatement(
            actions=["logs:CreateLogGroup", "logs:CreateLogStream", "logs:PutLogEvents"],
            resources=[f"arn:aws:logs:{self.region}:{self.account}:log-group:/aws/sagemaker/*"],
        ))

        # 4. SageMaker Transform role (used as the Model's execution role too)
        self.sm_transform_role = iam.Role(
            self, "SmTransformRole",
            assumed_by=iam.ServicePrincipal("sagemaker.amazonaws.com"),
        )
        self.bucket.grant_read_write(self.sm_transform_role)
        self.sm_transform_role.add_to_policy(iam.PolicyStatement(
            actions=["logs:CreateLogGroup", "logs:CreateLogStream", "logs:PutLogEvents"],
            resources=[f"arn:aws:logs:{self.region}:{self.account}:log-group:/aws/sagemaker/*"],
        ))

        # 5. Lambda write-results role (write-only to DynamoDB, read-only on the
        # batch-transform-output prefix)
        self.lambda_write_role = iam.Role(
            self, "LambdaWriteResultsRole",
            assumed_by=iam.ServicePrincipal("lambda.amazonaws.com"),
        )
        self.bucket.grant_read(self.lambda_write_role, "batch-transform-output/*")
        self.table.grant_write_data(self.lambda_write_role)
        self.lambda_write_role.add_to_policy(iam.PolicyStatement(
            actions=["logs:CreateLogGroup", "logs:CreateLogStream", "logs:PutLogEvents"],
            resources=[f"arn:aws:logs:{self.region}:{self.account}:log-group:/aws/lambda/*"],
        ))

        # 6. Lambda API role (read-only)
        self.lambda_api_role = iam.Role(
            self, "LambdaApiRole",
            assumed_by=iam.ServicePrincipal("lambda.amazonaws.com"),
        )
        self.table.grant_read_data(self.lambda_api_role)
        self.lambda_api_role.add_to_policy(iam.PolicyStatement(
            actions=["logs:CreateLogGroup", "logs:CreateLogStream", "logs:PutLogEvents"],
            resources=[f"arn:aws:logs:{self.region}:{self.account}:log-group:/aws/lambda/*"],
        ))

        # 7. Step Functions pipeline role -- the big one. Orchestrates Glue,
        # all SageMaker job types, SSM (model registry), and invokes the
        # write-results Lambda. Job-name-scoped resource patterns mirror
        # exactly what's already proven in the hand-built statemachine.json.
        self.sfn_role = iam.Role(
            self, "SfnPipelineRole",
            assumed_by=iam.ServicePrincipal("states.amazonaws.com"),
        )
        self.sfn_role.add_to_policy(iam.PolicyStatement(
            actions=["glue:StartJobRun", "glue:GetJobRun", "glue:GetJobRuns", "glue:BatchStopJobRun"],
            resources=[f"arn:aws:glue:{self.region}:{self.account}:job/hpv-feature-etl-v2"],
        ))
        self.sfn_role.add_to_policy(iam.PolicyStatement(
            actions=["sagemaker:CreateProcessingJob", "sagemaker:DescribeProcessingJob",
                     "sagemaker:StopProcessingJob", "sagemaker:AddTags"],
            resources=[f"arn:aws:sagemaker:{self.region}:{self.account}:processing-job/hpv-feature-processing-*"],
        ))
        self.sfn_role.add_to_policy(iam.PolicyStatement(
            actions=["sagemaker:CreateTrainingJob", "sagemaker:DescribeTrainingJob",
                     "sagemaker:StopTrainingJob", "sagemaker:AddTags"],
            resources=[f"arn:aws:sagemaker:{self.region}:{self.account}:training-job/hpv-risk-training-*"],
        ))
        self.sfn_role.add_to_policy(iam.PolicyStatement(
            actions=["sagemaker:CreateModel", "sagemaker:DescribeModel",
                     "sagemaker:DeleteModel", "sagemaker:AddTags"],
            resources=[f"arn:aws:sagemaker:{self.region}:{self.account}:model/hpv-risk-model-*"],
        ))
        self.sfn_role.add_to_policy(iam.PolicyStatement(
            actions=["sagemaker:CreateTransformJob", "sagemaker:DescribeTransformJob",
                     "sagemaker:StopTransformJob", "sagemaker:AddTags"],
            resources=[f"arn:aws:sagemaker:{self.region}:{self.account}:transform-job/hpv-risk-transform-*"],
        ))
        self.sfn_role.add_to_policy(iam.PolicyStatement(
            actions=["iam:PassRole"],
            resources=[
                self.sm_processing_role.role_arn,
                self.sm_training_role.role_arn,
                self.sm_transform_role.role_arn,
            ],
        ))
        self.sfn_role.add_to_policy(iam.PolicyStatement(
            actions=["events:PutTargets", "events:PutRule", "events:DescribeRule"],
            resources=[f"arn:aws:events:{self.region}:{self.account}:rule/StepFunctionsGetEventsFor*"],
        ))
        self.sfn_role.add_to_policy(iam.PolicyStatement(
            actions=["ssm:GetParameter", "ssm:PutParameter"],
            resources=[f"arn:aws:ssm:{self.region}:{self.account}:parameter/hpv-mlops-v2/current-model-artifact"],
        ))
        # lambda:InvokeFunction for the write-results function is added once
        # that Lambda exists (next step) -- needs its function ARN as a
        # resource, which we don't have yet at this point in the build.

        # ------------------------------------------------------------------
        # Deploy all pipeline assets (Glue script, processing script,
        # packaged training code, scoring input, and the raw dataset) in
        # one consolidated deployment. The local `deploy_assets/` folder's
        # subfolder structure mirrors the exact S3 key structure the
        # pipeline expects -- CDK uploads it as-is, no separate manual
        # `aws s3 cp` commands needed for any of these.
        # ------------------------------------------------------------------
        self.assets_deployment = s3_deployment.BucketDeployment(
            self, "PipelineAssetsDeployment",
            sources=[s3_deployment.Source.asset("../deploy_assets")],
            destination_bucket=self.bucket,
        )

        # ------------------------------------------------------------------
        # Glue ETL job
        # ------------------------------------------------------------------
        self.glue_job = glue.CfnJob(
            self, "HpvFeatureEtlJob",
            name="hpv-feature-etl-v2",
            role=self.glue_role.role_arn,
            command=glue.CfnJob.JobCommandProperty(
                name="glueetl",
                script_location=f"s3://{self.bucket.bucket_name}/scripts/glue_etl_job.py",
                python_version="3",
            ),
            glue_version="4.0",
            worker_type="G.1X",
            number_of_workers=2,
            timeout=15,
            default_arguments={
                "--job-bookmark-option": "job-bookmark-disable",
                "--TempDir": f"s3://{self.bucket.bucket_name}/tmp/",
                "--enable-metrics": "true",
                "--enable-continuous-cloudwatch-log": "true",
            },
        )
        # Explicit dependency: the script must actually exist in S3 before
        # the Glue job resource references its location.
        self.glue_job.node.add_dependency(self.assets_deployment)

        # ------------------------------------------------------------------
        # Lambda: write_results (internal, invoked by Step Functions only)
        # ------------------------------------------------------------------
        self.write_results_function = lambda_.Function(
            self, "WriteResultsFunction",
            runtime=lambda_.Runtime.PYTHON_3_12,
            handler="write_results.handler",
            code=lambda_.Code.from_asset("../lambda/write_results"),
            role=self.lambda_write_role,
            timeout=Duration.seconds(60),
            memory_size=256,
            environment={"TABLE_NAME": self.table.table_name},
        )

        # Now that the function exists, grant Step Functions permission to
        # invoke it -- deferred from the IAM step since we needed the
        # function's ARN, which didn't exist yet at that point.
        self.sfn_role.add_to_policy(iam.PolicyStatement(
            actions=["lambda:InvokeFunction"],
            resources=[self.write_results_function.function_arn],
        ))

        # ------------------------------------------------------------------
        # Lambda: read-side API (FastAPI + Mangum)
        #
        # Code.from_asset points at a folder that ALREADY contains the
        # pre-installed dependencies (fastapi, mangum, pydantic, including
        # the compiled pydantic_core binary) -- built manually via the same
        # Docker-free `pip install --platform manylinux2014_x86_64 ...`
        # approach proven earlier in this project. CDK just zips this
        # folder as-is; no Docker-based bundling involved.
        # ------------------------------------------------------------------
        self.api_function = lambda_.Function(
            self, "RiskApiFunction",
            runtime=lambda_.Runtime.PYTHON_3_12,
            handler="app.handler",
            code=lambda_.Code.from_asset("../api"),
            role=self.lambda_api_role,
            timeout=Duration.seconds(30),
            memory_size=512,
            environment={"TABLE_NAME": self.table.table_name},
        )

        # Public Function URL -- same approach we landed on manually, given
        # the diagnosed account-level restriction on public Lambda access.
        # Declared here so the full architecture is represented in code,
        # even though invoking it publicly may currently be blocked for the
        # same account-level reason documented in the project README.
        self.api_function_url = self.api_function.add_function_url(
            auth_type=lambda_.FunctionUrlAuthType.NONE,
        )

        # ------------------------------------------------------------------
        # Step Functions state machine
        #
        # Reuses our EXACT, already-debugged statemachine.json rather than
        # rewriting the orchestration logic in CDK's fluent API -- that
        # logic took real iteration to get right (the AddTags gaps, the
        # ResultPath bug, etc.) and re-deriving it here would risk
        # reintroducing bugs we already fixed once.
        #
        # The file DOES need its old hardcoded values (job/role/bucket/
        # table names from the manually-built v1 resources) replaced with
        # references to the new v2 resources -- done here as straightforward
        # text substitution on the JSON before parsing it.
        # ------------------------------------------------------------------
        import json

        with open("../step_functions/statemachine.json") as f:
            definition_text = f.read()

        substitutions = {
            '"hpv-feature-etl"': '"hpv-feature-etl-v2"',
            "rwk-hpv-mlops": self.bucket.bucket_name,
            "arn:aws:iam::041904915024:role/sm-hpv-processing-role": self.sm_processing_role.role_arn,
            "arn:aws:iam::041904915024:role/sm-hpv-training-role": self.sm_training_role.role_arn,
            "arn:aws:iam::041904915024:role/sm-hpv-transform-role": self.sm_transform_role.role_arn,
            "/hpv-mlops/current-model-artifact": "/hpv-mlops-v2/current-model-artifact",
            '"hpv-write-results"': f'"{self.write_results_function.function_name}"',
        }
        for old, new in substitutions.items():
            definition_text = definition_text.replace(old, new)

        # sanity check: fail the synth loudly if any old hardcoded value
        # somehow survived the substitution, rather than silently deploying
        # a state machine that secretly still points at the old resources
        assert "rwk-hpv-mlops" not in definition_text, "Old bucket name still present after substitution!"
        assert "041904915024" not in definition_text, "Old account-specific role ARN still present after substitution!"

        self.state_machine = sfn.StateMachine(
            self, "HpvMlopsPipeline",
            state_machine_name="hpv-mlops-pipeline-v2",
            definition_body=sfn.DefinitionBody.from_string(definition_text),
            role=self.sfn_role,
        )
        self.state_machine.node.add_dependency(self.assets_deployment)

        # ------------------------------------------------------------------
        # EventBridge scheduled trigger -- designed back at the very start
        # of this project but never actually built until now (every run
        # until this point was triggered manually). Nightly, with
        # retrain_requested=true so a fresh model trains on each scheduled
        # run -- matches the "conditional retrain" design intent, though a
        # real production schedule might set this to false most nights and
        # true weekly instead.
        # ------------------------------------------------------------------
        self.schedule_rule = events.Rule(
            self, "HpvPipelineSchedule",
            schedule=events.Schedule.cron(hour="2", minute="0"),  # 02:00 UTC nightly
        )
        self.schedule_rule.add_target(
            targets.SfnStateMachine(
                self.state_machine,
                input=events.RuleTargetInput.from_object({"retrain_requested": True}),
            )
        )